-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 16:03:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema abcjobportal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema abcjobportal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abcjobportal` DEFAULT CHARACTER SET utf8 ;
USE `abcjobportal` ;

-- -----------------------------------------------------
-- Table `abcjobportal`.`User`
-- -----------------------------------------------------
CREATE TABLE `User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `User_Firstname` VARCHAR(45) NOT NULL,
  `User_Lastname` VARCHAR(45) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  `User_password` VARCHAR(45) NOT NULL,
  `User_country` VARCHAR(45) NOT NULL,
  `User_city` VARCHAR(45) NOT NULL,
  `User_address` VARCHAR(45) NOT NULL,
  `User_company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `User_email_UNIQUE` (`User_email` ASC),
  UNIQUE INDEX `User_password_UNIQUE` (`User_password` ASC))
ENGINE = InnoDB;

INSERT INTO user (User_Firstname,User_Lastname,User_email, User_password,User_country, User_city, User_address, User_company_name) VALUES ('John','Mayer','johnmayer@gmail.com','qwe1123','Myanmar','Yangon','Boyarnyunt Street','Rox'),
																																		('Ross','Geller','rossgeller@gmail.com','AWD221A','Myanmar','Yangon','Pyay Street','FACEBOOK'),
																																		('Jason','Noria','jasonnoria@gmail.com','ighwes123','Myanmar','Yangon','Ahlone Street','Microsoft'),
                                                                                                                                        ('Jason','Noria','jasonnoria@gmail.com','ighwes123','Myanmar','Yangon','Ahlone Street','Microsoft'),
																																		('Joey','Smith','Joeysmith@gmail.com','485648swdw','Myanmar','Yangon','Hla thar Street','7seventh');
INSERT INTO user (User_Firstname,User_Lastname,User_email, User_password,User_country, User_city, User_address, User_company_name) VALUES ('John','Mayer','johnmaye@gmail.com','1','Myanmar','Yangon','Boyarnyunt Street','Rox');
SELECT * FROM user;
DELETE FROM user
where userid = 7;
-- Table `abcjobportal`.`Admin`
-- -----------------------------------------------------
CREATE TABLE `Admin` (
  `AdminId` INT NOT NULL AUTO_INCREMENT,
  `Admin_Username` VARCHAR(45) NOT NULL,
  `Admin_email` VARCHAR(45) NOT NULL,
  `Admin_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AdminId`),
  UNIQUE INDEX `Admin_email_UNIQUE` (`Admin_email` ASC) ,
  UNIQUE INDEX `Admin_password_UNIQUE` (`Admin_password` ASC) ,
  UNIQUE INDEX `Admin_Username_UNIQUE` (`Admin_Username` ASC) )
ENGINE = InnoDB;

INSERT INTO admin (Admin_username,Admin_email,Admin_password) VALUES ('Jack','jack@gmail.com','bnriu123'),
																	('Kevin','kevin@gmail.com','77asdwd'),
																	('Matt','matt@gmail.com','84wdsaw');
SELECT * FROM abcjobportal.admin;
-- -----------------------------------------------------
-- Table `abcjobportal`.`Post`
-- -----------------------------------------------------
CREATE TABLE `Post` (
  `PostId` INT NOT NULL AUTO_INCREMENT,
  `Post_description` VARCHAR(255) NULL,
  `Post_image` VARCHAR(100) NULL,
  `User_UserId` INT NOT NULL,
  `Admin_AdminId` INT NOT NULL,
  PRIMARY KEY (`PostId`),
  INDEX `fk_Post_User1_idx` (`User_UserId` ASC) ,
  INDEX `fk_Post_Admin1_idx` (`Admin_AdminId` ASC) ,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `abcjobportal`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Admin1`
    FOREIGN KEY (`Admin_AdminId`)
    REFERENCES `abcjobportal`.`Admin` (`AdminId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

UPDATE user
SET User_address= 'Sanchaung Street'
where userid=3;

SELECT * FROM USER;
-- -----------------------------------------------------
-- Table `abcjobportal`.`Comment`
-- -----------------------------------------------------
CREATE TABLE `Comment` (
  `CommentId` INT NOT NULL AUTO_INCREMENT,
  `Comment_description` VARCHAR(255) NULL,
  `User_UserId` INT NOT NULL,
  PRIMARY KEY (`CommentId`),
  INDEX `fk_Comment_User1_idx` (`User_UserId` ASC) ,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `abcjobportal`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abcjobportal`.`Education`
-- -----------------------------------------------------
CREATE TABLE `Education` (
  `EducationId` INT NOT NULL AUTO_INCREMENT,
  `Education_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EducationId`))
ENGINE = InnoDB;

INSERT INTO Education (Education_name) VALUES('Degree in computer'),
											('BSC'),
                                            ('Master in design thinking'),
                                            ('PhD in software engineering');
-- -----------------------------------------------------
-- Table `abcjobportal`.`Company`
-- -----------------------------------------------------
CREATE TABLE `Company` (
  `CompanyId` INT NOT NULL auto_increment,
  `Company_name` VARCHAR(45) NULL,
  `Company_email` VARCHAR(45) NULL,
  `Company_ph_number` INT NULL,
  `Company_country` VARCHAR(45) NULL,
  `Company_city` VARCHAR(45) NULL,
  `Company_address` VARCHAR(45) NULL,
  `Company_descrption` VARCHAR(45) NULL,
  `Company_sitelink` VARCHAR(45) NULL,
  PRIMARY KEY (`CompanyId`))
ENGINE = InnoDB;

insert into Company (Company_name, Company_email, Company_ph_number, Company_country, Company_city, Company_address, Company_descrption, Company_sitelink) values ('Tagopia', 'jcrotty0@taobao.com', '68445479', 'Portugal', 'Vila Verde', '0187 Victoria Court', 'Nam dui. Proin leo odio, porttir quis odio consequat varius. Integer ac leo.', 'http://jugem.jp/dui/maecenas/tristique.json?mauris=ulis&porta=d'),
																																										('Demimbu', 'dcloonan1@sohu.com', '51800188', 'France', 'Annecy', '5 Drewry Parkway', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibul', 'https://photobucket.com/non/velitdin&nulla=vacinit'),
																																										('Yotz', 'ayerborn2@about.me', '82190300', 'China', 'Xinzhou', '4 Gerald Point', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://ibm.com/convallis/tortor/risus/dapibus.jpg?ut=dolor&massa=quiullamc'),
																																										('Divape', 'leton3@prweb.com', '74076773', 'Sweden', 'Åhus', '81847 North Parkway', 'Vestibulum ante ipsum primis in faucibus orci luct quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convaum.', 'https://reverbnation.com/arcu/adipiscing.jsp?n');
SELECT * FROM company;
-- -----------------------------------------------------
-- Table `abcjobportal`.`Job`
-- -----------------------------------------------------
CREATE TABLE `Job` (
  `JobId` INT NOT NULL AUTO_INCREMENT,
  `Job_title` VARCHAR(45) NULL,
  `Job_type` VARCHAR(45) NULL,
  `Job_description` VARCHAR(255) NULL,
  `Company_CompanyId` INT NOT NULL,
  `Admin_AdminId` INT NOT NULL,
  PRIMARY KEY (`JobId`),
  INDEX `fk_Job_Company1_idx` (`Company_CompanyId` ASC) ,
  INDEX `fk_Job_Admin1_idx` (`Admin_AdminId` ASC) ,
  CONSTRAINT `fk_Job_Company1`
    FOREIGN KEY (`Company_CompanyId`)
    REFERENCES `abcjobportal`.`Company` (`CompanyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Job_Admin1`
    FOREIGN KEY (`Admin_AdminId`)
    REFERENCES `abcjobportal`.`Admin` (`AdminId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO job (Job_title,Job_type,Job_description,Company_CompanyId,Admin_AdminId) VALUES ('Software enginner','Technology', 'It is about a job where software engineer create a software for the company','1','1'),
																							('Graphic designer','Technology', 'It is about a job where graphic designer create a design for the company','2','2'),
																							('Accountant','Finance', 'It is about a job where accountant maintain a business for the company','3','3');
-- -----------------------------------------------------
-- Table `abcjobportal`.`Login`
-- -----------------------------------------------------
CREATE TABLE `Login` (
  `Login_Id` INT NOT NULL AUTO_INCREMENT,
  `User_UserId` INT NOT NULL,
  `Admin_AdminId` INT NOT NULL,
  PRIMARY KEY (`Login_Id`),
  INDEX `fk_Login_User1_idx` (`User_UserId` ASC) ,
  INDEX `fk_Login_Admin1_idx` (`Admin_AdminId` ASC) ,
  CONSTRAINT `fk_Login_User1`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `abcjobportal`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_Admin1`
    FOREIGN KEY (`Admin_AdminId`)
    REFERENCES `abcjobportal`.`Admin` (`AdminId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO login(login_Id,User_UserId,Admin_AdminId)VALUES('1','1','1'),
														('2','1','1'),
                                                        ('3','1','1'),
                                                        ('4','1','1');
                                                        
INSERT INTO login(Login_Id,User_UserId,Admin_AdminId)VALUES('12','2','2');
INSERT INTO login(Login_Id,User_UserId,Admin_AdminId)VALUES('13','1','1');
INSERT INTO login(Login_Id,User_UserId,Admin_AdminId)VALUES('14','3','3');
INSERT INTO login(Login_Id,User_UserId,Admin_AdminId)VALUES('15','4','3');
                                                        
SELECT * FROM login;
-- -----------------------------------------------------
-- Table `abcjobportal`.`Forgetpassword`
-- -----------------------------------------------------
CREATE TABLE `Forgetpassword` (
  `ForgetpasswordId` INT NOT NULL AUTO_INCREMENT,
  `Forgetpassword_code` INT(6) NULL,
  `Login_Login_Id` INT NOT NULL,
  PRIMARY KEY (`ForgetpasswordId`),
  UNIQUE INDEX `Forgetpassword_code_UNIQUE` (`Forgetpassword_code` ASC) ,
  INDEX `fk_Forgetpassword_Login1_idx` (`Login_Login_Id` ASC) ,
  CONSTRAINT `fk_Forgetpassword_Login1`
    FOREIGN KEY (`Login_Login_Id`)
    REFERENCES `abcjobportal`.`Login` (`Login_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO forgetpassword(forgetpassword_code,Login_Login_Id)VALUES('185592','6'),
																('851544','4'),
                                                                ('978248','9');
-- -----------------------------------------------------
-- Table `abcjobportal`.`User_has_Education`
-- -----------------------------------------------------
CREATE TABLE `User_has_Education` (
  `User_UserId` INT NOT NULL,
  `Education_EducationId` INT NOT NULL,
  PRIMARY KEY (`User_UserId`, `Education_EducationId`),
  INDEX `fk_User_has_Education_Education1_idx` (`Education_EducationId` ASC) ,
  INDEX `fk_User_has_Education_User1_idx` (`User_UserId` ASC) ,
  CONSTRAINT `fk_User_has_Education_User1`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `abcjobportal`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Education_Education1`
    FOREIGN KEY (`Education_EducationId`)
    REFERENCES `abcjobportal`.`Education` (`EducationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO user_has_education(User_UserId,Education_EducationId) VALUES ('1','1'),
																		('2','2'),
                                                                        ('3','3'),
                                                                        ('4','4');
-- -----------------------------------------------------
-- Table `abcjobportal`.`Job_has_Education`
-- -----------------------------------------------------
CREATE TABLE `Job_has_Education` (
  `Job_JobId` INT NOT NULL,
  `Education_EducationId` INT NOT NULL,
  PRIMARY KEY (`Job_JobId`, `Education_EducationId`),
  INDEX `fk_Job_has_Education_Education1_idx` (`Education_EducationId` ASC) ,
  INDEX `fk_Job_has_Education_Job1_idx` (`Job_JobId` ASC) ,
  CONSTRAINT `fk_Job_has_Education_Job1`
    FOREIGN KEY (`Job_JobId`)
    REFERENCES `abcjobportal`.`Job` (`JobId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Job_has_Education_Education1`
    FOREIGN KEY (`Education_EducationId`)
    REFERENCES `abcjobportal`.`Education` (`EducationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO job_has_education(Job_JobId,Education_EducationId) VALUES ('1','1'),
																		('2','2'),
                                                                        ('3','3');

-- -----------------------------------------------------
-- Table `abcjobportal`.`User_has_Job`
-- -----------------------------------------------------
CREATE TABLE `User_has_Job` (
  `User_UserId` INT NOT NULL,
  `Job_JobId` INT NOT NULL,
  PRIMARY KEY (`User_UserId`, `Job_JobId`),
  INDEX `fk_User_has_Job_Job1_idx` (`Job_JobId` ASC) ,
  INDEX `fk_User_has_Job_User1_idx` (`User_UserId` ASC) ,
  CONSTRAINT `fk_User_has_Job_User1`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `abcjobportal`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Job_Job1`
    FOREIGN KEY (`Job_JobId`)
    REFERENCES `abcjobportal`.`Job` (`JobId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO user_has_job(User_UserId,Job_JobId) VALUES ('1','1'),
														('2','2'),
														('3','3');
												
INSERT INTO comment(comment_description,User_UserId)VALUES ('In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.','1'),
															('Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vesatibulum eget, vulputate ut, ultrices vel, augue.','1');

INSERT INTO post(post_description,Post_image,User_UserId,Admin_AdminId) VALUES ('ed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices matt','http://dummyimage.com/161x128.jpg/cc0000/ffffff','1','1'),
																				('ed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices matt','http://dummyimage.com/199x128.bmp/cc0000/ffffff','2','2');

SELECT UserId,User_Firstname, User_Lastname,User_email,PostId,Post_description,Post_image
FROM user INNER JOIN post ON user.UserId=post.User_UserId;

INSERT INTO company(Job_title,Job_type,Job_description,Company_CompanyId,Admin_AdminId)VALUES('Consultant','Finance','Consultant is a part of finance'),
	('Executive manager','Finance','Executive manager is a part of finance');
    
insert into company (Company_name, Company_email, Company_ph_number, Company_country, Company_city, Company_address, Company_descrption, Company_sitelink) values ('Cogidoo', 'astallybrass0@npr.org', '4815806', 'Argentina', 'Gualeguaychú', '8 Glendale Terrace', 'Quisque porta volutpat erat. Quisque erateg', 'http://linkedin.com/tincidunt/in/leo.html?pulvins=dui&vel=vel&augue=nisl&s=purus&duis=mollis');
insert into company (Company_name, Company_email, Company_ph_number, Company_country, Company_city, Company_address, Company_descrption, Company_sitelink) values ('Photobean', 'amartini1@npr.org', '8459985', 'Brazil', 'Joinville', '0313 Anderson Drive', 'Nulla tellus. In sagittis dui vel nisl. Duisuam a odqat.', 'http://baidu.com/nulla/mollis/molessi');
insert into company (Company_name, Company_email, Company_ph_number, Company_country, Company_city, Company_address, Company_descrption, Company_sitelink) values ('Edgewire', 'eshellsheere2@e-recht24.de', '8355563', 'Thailand', 'Nikhom Phattana', '5 Oak Parkway', 'In blandit ultrices enim. Lorem ipsum dolous id sa Viv. Pellentnc.', 'http://noaa.gov/quisque/arcu.png?quam=lectus&sap&tortor=justo&risus');


SELECT Company_name,Company_email,Company_ph_number,JobId FROM company LEFT JOIN job ON company.companyId=job.company_companyId;

SELECT Count(UserId), User_address
from user
group by User_address
order by Count(UserId) DESC;

delimiter //
create procedure Selectuser(in ad varchar(45))
begin
select * from user where User_address=ad;
end//
call Selectuser ('Hla thar Street');

delimiter //
create trigger abc
after insert 
on login
for each row
begin
	insert into forgetpassword values('4',new.Login_Id,'827291');
end;//

use abcjobportal;

select * from login;
select * from forgetpassword;

drop trigger abc;

insert into abcjobportal.login values(17,1,2);	

select * from education;

create user DBDesigner@localhost identified by 'designerpassword';
create user Application@localhost identified by 'applicationpassword';


grant all on abcjobportal.* TO DBDesigner@localhost;
grant create,select,update,delete,execute on abcjobportal.* TO Application@localhost;
use abcjobportal;
show grants for DBDesigner@localhost;

show grants for Application@localhost;


SELECT * FROM comment;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
